version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_app
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ml_database
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge